### ISSUE TITLE
\closing{Mit freundlichen Grüßen} is displayed in the wrong position

### ISSUE THREAD

**Issue by bshOriginal** [PanCakeConnaisseur/latex-briefvorlage-din-5008#5]
Hi,
when the form name gets too long - as it is quite often with foreign names - the closing text
\closing{Mit freundlichen Grüßen} 
is displayed at an inappropriate position (way far to the right). 

An example for a too long 'fromname':
\setkomavar{fromname}{Anton Absender Antonia Absenderin Antonella Absenderin3}

Example:
[Latex-Briefvorlage.pdf](https://github.com/PanCakeConnaisseur/latex-briefvorlage-din-5008/files/8539704/Latex-Briefvorlage.pdf)

Kind regards,
bsh

**Comment by alexeyabel** [comment]
This can also be solved using the `%\renewcommand*{\raggedsignature}{\raggedright}` statement. I adjusted the comment above it in https://github.com/PanCakeConnaisseur/latex-briefvorlage-din-5008/commit/505e47b18f86fb2ca702c009e4fda2186a66248d.
